FROM lambdadeveloper/compilouit:angular

LABEL maintainer="John Murowaniecki <john@compilou.com.br>"
LABEL codeAuthor="John Murowaniecki <john@compilou.com.br>"

WORKDIR /app
COPY ./ /app

RUN yarn install
RUN yarn cache clean
RUN yarn run build

FROM lambdadeveloper/compilouit:node AS web

WORKDIR /application

COPY ./../api /application
COPY --from=0 /app/dist/site /application/public

RUN yarn install --verbose

CMD ["npm", "run-script", "λ"]
